### PR TITLE
Switch to jovial_svg for faster rendering

### PR DESCRIPTION
**Pull request by bgoncharuck**
## Description

I switched your plugin to jovial_svg and generated SI files for it.
You can compare the speed using a CustomScrollView with all country flags in it.
Only res/si/ are loaded into assets of applications and SVGs used as source for
`dart run jovial_svg:svg_to_si res/svg/*`

Also I removed dependency on intl.
Can revert it, if you need it.
But I didn't find any dependency on it through your project.

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [X] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

**Review by nosovk — APPROVED** [review]
seems cool

**Comment by arturograu** [comment]
Thank you very much! I will take a look when I find some time 👍🏻

**Comment by bgoncharuck** [comment]
Take your time =)
You need an app with ListView or CustomScrollView with all countries to see the difference of performance.
I'm already using this modification in some of my project, and it turned to be the most performant solution for flags out there.

**Comment by hectorAguero** [comment]
Hey @bgoncharuck, I know this a 2y old MR, but what are you using nowadays? also I saw in this repo a [MR for caching](https://github.com/arturograu/country_flags/pull/40).

I'm think on forking this package to use webp images to improve performance, but don't if it make sense really

**Pull request merged**
